name: Publish Extension Firefox

on:
  workflow_dispatch:

jobs:
  publish:
    name: Publish Extension to Store
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Download Extension
        uses: robinraju/release-downloader@v1.8
        with:
          latest: true
          fileName: "*.zip"
      - name: Download Source Code
        run: |
          curl -L -o source-code.zip $(curl -s https://api.github.com/repos/ttop32/MouseTooltipTranslator/releases/latest | jq -r '.zipball_url')
          unzip source-code.zip -d source-code
          
      - name: Get Release File Name
        run: echo "RELEASE_FILE=$(ls | grep *.firefox.zip)" >> $GITHUB_ENV
      - name: Test
        run: echo ${{env.RELEASE_FILE}}

      - name: Publish to store
        uses: PlasmoHQ/bpp@v3.8.0
        with:
          keys: ${{ secrets.FIREFOX_BPP_KEYS }}
          firefox-file: "${{env.RELEASE_FILE}}"
